### ISSUE TITLE
The run_covid_fauci.py does not run.

### ISSUE THREAD

**Issue by Kaushal-13** [zihaohe123/wiki-enhanced-stance-detection#2]
Hello There, I am not sure what could have caused the issue but when I try to run the above task it gives the following error.

"unrecognized arguments: =fauci-lr=1e-05-bs=32-covid-twitter-bert-wiki=bert-base-n_layers_fz_wiki=11-n_gpus=2.txt"
Thanks.

**Comment by Kaushal-13** [comment]
Also could you help me in understanding where the data is finally saved??

**Comment by zihaohe123** [comment]
Hi Kaushal, it seems that you don't have a whitespace to separate the different parameters. You should put the data under data/covid19-stance folder. And please follow instructions in README on how to access the data.

**Comment by Kaushal-13** [comment]
Thanks for the reply Sir, I tried naking the changes and it is working fine.
Regards.
