### ISSUE TITLE
Epoch is set at 5

### ISSUE THREAD

**Issue by WreckItBoss** [zihaohe123/wiki-enhanced-stance-detection#7]
Hello, I sent you an email wondering why the biden would always end at 5 epochs and I realized that in run_pstance_biden the max epoch is set at 5. It would be wonderful if it gets fixed! Thank you!

**Comment by zihaohe123** [comment]
Hi there,

Thanks for pointing this out! Right you should increase the number of epochs. I'll also make this change to the code.

Best,
Zihao
